# your domain
domain: by-mini.herokuapp.com

# database url
database_url: ""

# cloudflare api
cf_email: "lskonbar@gmail.com"
cf_key: "fYl1JNpSdnLONGNpfCWb6mjsN_Rrg1vJKFXkP7Og"

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://by-mini.herokuapp.com/source.yaml
